apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Pipeline

on:
  push:
    branches: 
         - dev
env:
  APPLICATION_NAME: startupapp
  IMAGE_NAME: saas-sagemaker
  IMAGE_VER: latest

jobs:
  build_image_push_to_ECR:
    steps:
    - name: Checkout
      uses: cloudbees-io/checkout@v1
    # see: https://github.com/aws-actions/configure-aws-credentials
    - name: Configure AWS Credentials
      uses: cloudbees-io/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ss_aws_access_key_id }}
        aws-secret-access-key: ${{ secrets.ss_aws_secret_access_key }}
        aws-region: us-east-1

    - uses: cloudbees-io/configure-oci-credentials@v1
      name: Setup Docker Hub Registry
      with:
        registry: index.docker.io
        username: ${{ vars.SUM_DOCKER_USERNAME }}
        password: ${{ secrets.SUM_DOCKER_PASSWORD }}

    - name: Build a container image with Kaniko
      uses: cloudbees-io/kaniko@v1
      with:
          dockerfile: Dockerfile
          context: .
          destination: ${{ vars.SUM_DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VER }}
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1,BUILDKIT_INLINE_CACHE=1
          labels: maintainer=Sumeet Singh,version=${{ env.IMAGE_VER }}

        
  submit_training_job:
    needs: [build_image_push_to_ECR]
    steps:
    - name: Checkout
      uses: cloudbees-io/checkout@v1
      
    - name: Fire SageMaker
      id: sm_train
      uses: docker://ssingh08/saas-sagemaker:latest
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.ss_aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.ss_aws_secret_access_key }}
        AWS_DEFAULT_REGION: us-east-1
        BUCKET_NAME: sample-sagemaker-saas
        PREFIX: result
        IAM_ROLE_NAME: arn:aws:iam::324005994172:role/awslambda-saas
        GITHUB_SHA: ${{ cloudbees.scm.sha }}
      run: |
        pip install --no-cache-dir --upgrade awscli pandas boto3 sagemaker requests fsspec s3fs tabulate
        python training-job.py
        cat details.txt >> report.md
        cml-send-comment report.md 
