apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Pipeline

on:
  push:
    branches: 
      - dev
env:
  APPLICATION_NAME: startupapp

jobs:
  build_image_push_to_ECR:
    steps:
    - name: Checkout
      uses: cloudbees-io/checkout@v1
    # see: https://github.com/aws-actions/configure-aws-credentials
    - name: Configure AWS Credentials
      uses: cloudbees-io/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ss_aws_access_key_id }}
        aws-secret-access-key: ${{ secrets.ss_aws_secret_access_key }}
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: cloudbees-io/configure-ecr-credentials@v1

    - name: Build, tag, and push image to Amazon ECR
      uses: cloudbees-io/kaniko@v1
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: saas-sagemaker
        IMAGE_TAG: latest
      with:
          dockerfile: Dockerfile
          context: .
          destination: 324005994172.dkr.ecr.us-east-1.amazonaws.com/saas-sagemaker
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1,BUILDKIT_INLINE_CACHE=1
          labels: maintainer=Sumeet,version=1.0.0
        
  submit_training_job:
    needs: [build_image_push_to_ECR]
    steps:
    - name: Fire SageMaker
      id: sm_train
      uses: docker://dvcorg/cml-py3:latest
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.ss_aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.ss_aws_secret_access_key }}
        AWS_DEFAULT_REGION: us-east-1
        BUCKET_NAME: sample-sagemaker-saas
        PREFIX: result
        IAM_ROLE_NAME: ${{ secrets.IAM_ROLE_NAME }}
        GITHUB_SHA: ${{ cloudbees.scm.sha }}
      run: |
        pip install --no-cache-dir --upgrade awscli pandas boto3 sagemaker requests fsspec s3fs tabulate
        python training-job.py
        cat details.txt >> report.md
        cml-send-comment report.md 
      