name: deploy_endpoint
on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    steps:
    - name: Checkout Repository
    - uses: cloudbees-io/checkout@v1

    
    - name: Fire SageMaker
    - uses: docker://dvcorg/cml-py3:latest
      id: sm_train
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        pip install --no-cache-dir --upgrade awscli pandas boto3 sagemaker requests
        python deploy.py
